### ISSUE TITLE
What is required to add designer support for ScrollView

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#114]
To use `ScrollView` you must set `ContentSize`.  Editor support will require:

- [ ] A designer for `Size` struct
- [ ] A sensible default in `ViewFactory`
- [ ] Possibly some drag and drop adjustment so that when dropping controls into the `ScrollView` when it is scrolled down works.
- [ ] Code generation for `Size` (`ContentSize`)
- [ ] All the tests
- [ ] A way to drag and resize the view when it doesn't have any borders (already solved in #106)

Here is the minimum code to produce a ScrollView.  Setting `ContentSize` is absolutely vital.  Without it stuff just doesn't work properly.

```csharp
using Terminal.Gui;

Application.Init();
var win = new Window("Example App (Ctrl+Q to quit)");

var scr = new ScrollView()
{
    Width = Dim.Fill(),
    Height = Dim.Fill(),
    ShowVerticalScrollIndicator = true
};
scr.ContentSize = new Size(30, 500);
scr.Add(new BigView());

win.Add(scr);
Application.Run(win);
Application.Shutdown();

class BigView : View
{
    public BigView()
    {
        Height = 500;
        Width = 30;
    }
    public override void Redraw(Rect bounds)
    {
        base.Redraw(bounds);

        for(int x=0;x<30;x++)
        {
            for (int y = 0; y < 500; y++)
            {
                var digit = y % 10;
                AddRune(x, y, digit.ToString()[0]);
            }
        }
    }
}
```

**Comment by BDisp** [comment]
If you mean that you want the scroll bars are show even without add contents, for now it's not working because there are a bug. This PR https://github.com/gui-cs/Terminal.Gui/pull/2136 will fix it. So, you only need do the following and the vertical scroll bar will be showed if the console width is greater than 30.

```cs
using Terminal.Gui;

Application.Init();
var win = new Window("Example App (Ctrl+Q to quit)");

var scr = new ScrollView()
{
    Width = Dim.Fill(),
    Height = Dim.Fill(),
    ContentSize = new Size(30, 500)
};

win.Add(scr);
Application.Run(win);
Application.Shutdown();
}
```

**Comment by tznind** [comment]
> If you mean that you want the scroll bars are show even without add contents,

Sorry, this issue was not about any bugs just a small exploration of minimum code to generate for ScrollView and scope out what would be required to add it to the designer.  Thanks for the more condensed code.
