### ISSUE TITLE
MenuBar private variables should be cammel case

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#151]
Currently naming starts with caps which is wrong for private variables:

```csharp
private Terminal.Gui.MenuBar menubar;
private Terminal.Gui.MenuBarItem _FileF9;
private Terminal.Gui.MenuItem RunnewTask;
private Terminal.Gui.MenuItem Exit;
```

**Comment by BDisp** [comment]
Do you mean that private variables should be started with lower case without underscore and subsequent with upper case, like this bellow?

```cs
menuBar
fileF9
runnewTask
exit

```
Otherwise I think only public variables should be start with a upper case letter.

**Comment by tznind** [comment]
> Otherwise I think only public variables should be start with a upper case letter.

Yup that is the case after #154 

There is also a suffix added now.

This is now matching what you get with Winforms:

![image](https://user-images.githubusercontent.com/31306100/202188980-2e61c6ad-3ec1-449e-9571-ec40f8d847ae.png)

```csharp
private MenuStrip menuStrip1;
private ToolStripMenuItem testToolStripMenuItem;
private ToolStripMenuItem doubleTestToolStripMenuItem;
```
_windows forms designer generated code_

![image](https://user-images.githubusercontent.com/31306100/202189341-9e342bde-e9e1-46c7-a005-6418d864fe73.png)

```csharp
private Terminal.Gui.MenuBar menubar;
private Terminal.Gui.MenuBarItem testMenu;
private Terminal.Gui.MenuItem doubletestMenuItem;
```
_terminal gui designer generated code_

**Comment by tznind** [comment]
Although now I can see that the winforms designer is also auto capitalizing where it takes out a space, I think I will add that in.
