### ISSUE TITLE
MenuBar can appear below other Views

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#153]
Vertical z order of controls in Terminal.Gui is determined by the order they are added to the `View` as is tab order.  TerminalGuiDesigner has a method `public static IEnumerable<View> OrderViewsByScreenPosition(IEnumerable<View> views)` which typically gives a sensible tab order.  But since MenuBar appears at 0,0 (typically) it is the first added to the parent view.  This results in it being at the bottom of the z order.

![image](https://user-images.githubusercontent.com/31306100/202173664-4870acc0-ea22-47be-86c8-dde3cfc1db70.png)

Before we start implementing a z-order feature (bring to front / send to back) lets take a quick fix to adjust `OrderViewsByScreenPosition` so that MenuBar gets treated as last.

**Comment by BDisp** [comment]
One question. That `MenuBar` is part of the app that is been build, right? Why not put the others views inside a container first, like `Window` and thus the `Toplevel` `PositionToplevel` method will ensure the container to be re-positioned.

**Comment by tznind** [comment]
Yup that is absolutely sensible however I think we (and the designer) should handle other use cases too  for example having multiple menus in other Views:

![image](https://user-images.githubusercontent.com/31306100/202178555-b51c9b99-fbd8-46c1-a50d-4bbcbe54d563.png)
