### ISSUE TITLE
Incorrectly adding Border in .Designer.cs (e.g. to label)

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#22]
Found this issue but was not able to reproduce how it occurs.

Tool produces the following (see below).  Problem is `this.label2.Border` is null when trying to load/use the class the code is produced for.

```
this.label2 = new Terminal.Gui.Label();
this.label2.Width = 4;
this.label2.Height = 1;
this.label2.X = 17;
this.label2.Y = 7;
this.label2.Data = "label2";
this.label2.Text = "Heya";
this.label2.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
this.label2.Border.BorderBrush = Terminal.Gui.Color.Black;
this.label2.Border.Effect3D = false;
this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
this.Add(this.label2);
```

**Comment by BDisp** [comment]
You have to create the Border type before use it:
`this.label2.Border = new Border();`


```cs
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace YourNamespace {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label2;
        
        private void InitializeComponent() {
	        this.label2 = new Terminal.Gui.Label();
	        this.label2.Width = 4;
	        this.label2.Height = 1;
	        this.label2.X = 17;
	        this.label2.Y = 7;
	        this.label2.Data = "label2";
	        this.label2.Text = "Heya";
	        this.label2.Border = new Border();
	        this.label2.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
	        this.label2.Border.BorderBrush = Terminal.Gui.Color.Black;
	        this.label2.Border.Effect3D = false;
	        this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
	        this.Add(this.label2);        
        }
    }
}

```

**Comment by BDisp** [comment]
I think you can add the `Border` type in the context menu above the `ColorScheme` and open his properties.

**Comment by tznind** [comment]
Yup, the current codebase works ok:  It allows you to edit Border if a `View` has one but **not** if a `View` does not have one.  

Currently border properties are exposed as subproperties so appear in the list of regular Properties that can be designed.  If we go deeper into adding borders to stuff or want to centralise border logic then adding a BorderEditor popup that lets you add/remove and edit styles might be sensible rather than having it piecemeal.

But given `Label` doesn't currently have a `Border` and theres no way in the designer to add one (now that #2  is closed and not merged).  I don't think we will see this specific issue again (not calling Border constructor).

**Comment by BDisp** [comment]
When I created the `Border` I intentional didn't instantiated because not all views want a border at all and if a view want a `Border` then must implemented it and handles his behavior, because the `View` class itself doesn't do nothing. But if it's more useful the `View` class can initialize immediately be setting `Border border = new Border ();`. If you want that please open an issue to add that change, please.
