### ISSUE TITLE
Why using menuOpen and not ContextMenu.IsShow in the Editor?

### ISSUE THREAD

**Issue by BDisp** [gui-cs/TerminalGuiDesigner#230]
Only a `ContextMenu` can be open at a time and so the `ContextMenu.IsShow` property is static. @tznind I don't know if there is some specific reason for you don't use it.

**Comment by tznind** [comment]
Not sure I follow, which part of the codebase is this?

**Comment by BDisp** [comment]
> Not sure I follow, which part of the codebase is this?

Here:
https://github.com/gui-cs/TerminalGuiDesigner/blob/5dd62b5f404814b3eb5ba3a55ecfac4f38880c32/src/UI/Editor.cs#L28

Here instead of this:
https://github.com/gui-cs/TerminalGuiDesigner/blob/5dd62b5f404814b3eb5ba3a55ecfac4f38880c32/src/UI/Editor.cs#L281
 you can use :
```cs
if (keyEvent.Key == this.keyMap.ShowContextMenu && !ContextMenu.IsShow)
```

**Comment by BDisp** [comment]
Not needed, so closing this.
