### ISSUE TITLE
Idea - Recreate demo gif in Windows Terminal with a posh theme?

### ISSUE THREAD

**Issue by jakenuts** [gui-cs/TerminalGuiDesigner#245]
Please feel free to ignore this, especially if the title already is impossible (not sure what compatibility this has with wt and or posh). 

This seems like such a cool idea & the demo gif sucked me in - but it nearly didn't due to the basic-batch blue background and notepad co-star. 

If it twere in a pretty dark WT shell (ala Spectre.Console) sort of view i'd have splurted coffee all over my bathtub. So perhaps its for the best. 

Anyhoo, technically masterful - aesthetically just a bit wobbly.

Thanks!

**Comment by tznind** [comment]
How is this? Better? Feel free to feedback and I can adjust and then update README.md to the new demo.

![TerminalGuiDesigner](https://github.com/gui-cs/TerminalGuiDesigner/assets/31306100/c2697162-1c87-4ae6-8530-799e4c0f62ca)

**Comment by jakenuts** [comment]
You are likely correct, and the updated demo definitely is an improvement. I think I'm just overly enamoured with spectre.console as an approach to getting people back to the command line and was excited to see another project with that goal in mind.

![image](https://github.com/gui-cs/TerminalGuiDesigner/assets/344606/6f898003-d4bf-4e32-8d80-1520a0c60392)
