### ISSUE TITLE
Allowing mouse double click in `BigListBox<T>` instead forcing to click in the Ok button.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/TerminalGuiDesigner#62]

**Comment by tznind** [comment]
Which UI(s) is this on?

**Comment by BDisp** [comment]
On "Create New View" and "Type of Control" UI's.

**Comment by tznind** [comment]
Ah right thx that is all `class BigListBox<T>` I think.  Its used all over the place.  Definetly worth adding that double click support

**Comment by tznind** [comment]
I'll make that a new issue #64
