### ISSUE TITLE
Replace the initial window instructions with a ContextMenu with the shortcuts.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/TerminalGuiDesigner#63]

**Comment by tznind** [comment]
I was going for something like the Visual Studio Code landing page on first open (see pic).  

The reason for this choice was:
- Make it clear that nothing is currently loaded (i.e. big black empty window)
- Make the transition from empty state to your view being loaded very clear 
- Introduce user as early as possible to the idea of using memorized shortcuts

But I like your idea of a menu.  Just so long as the above goals are preserved.  We definitely want key rebinding accessible from the launch page too (see #37)

![vs](https://user-images.githubusercontent.com/31306100/182128739-80704672-8669-40dc-9e86-c73f68aae06c.jpg)

**Comment by BDisp** [comment]
I understand your point of view. Since you liked the menu idea, I suggest if the user right click then a `ContextMenu` is open with the same actions.

**Comment by tznind** [comment]
Thats a good idea.  Or we might be able to just make a Menu that has the same color scheme as the current splash screen rather than it being manually drawn like it currently is.

**Comment by TonyHenrique** [comment]
Perhaps it could be interesting to do something similar to Visual Basic for DOS

![image](https://user-images.githubusercontent.com/6307623/188024493-628d8013-bec0-466d-978c-f8f9d5dd8df4.png)
https://www.cloudwisp.com/exploring-visual-basic-1-0-for-ms-dos/

**Comment by BDisp** [comment]
What can be done is redraw the dots on the Editor if a flag `ShowGrid` is enabled.

**Comment by tznind** [comment]
> Perhaps it could be interesting to do something similar to Visual Basic for DOS
 
I do like this gui with its floating toolboxes and designer top menu.  I particularly like the grid and anchors (as @BDisp has commented on).

Based on this feedback:
- I have created a new issue for ShowGrid and Anchors

But I think having designer menus and floating toolboxes is a much bigger task and would need a lot of work.  It would need to be **really good** before merging.  At the moment the users View being edited has full working area and everything is done via shortcuts or context menu (right click).  All 'designer tasks' take the user to a fresh fullscreen view (e.g. 'pick what control to add').   So it is super clear what is designer elements and which are ones the user has created.

**Comment by tznind** [comment]
@tig are you able to enable Discussions on this repo? I have read/write but I cannot see the Settings option (so presumably I lack that privellege after transfering to `gui-cs` org).

Once Discussions are on I can move the 'floating toolbars / designer menus' there.

**Comment by tig** [comment]
Done!

**Comment by tznind** [comment]
Thanks

**Comment by tznind** [comment]
Here is the discussion I have opened https://github.com/gui-cs/TerminalGuiDesigner/discussions/88
