### ISSUE TITLE
Another annoying thing is `ComboBox` not hiding the list on click but only by double clicking or clicking on the down symbol. I don't remember if there is any option to close on click.

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#64]
> Another annoying thing is `ComboBox` not hiding the list on click but only by double clicking or clicking on the down symbol. I don't remember if there is any option to close on click.

_Originally posted by @BDisp in https://github.com/gui-cs/TerminalGuiDesigner/issues/62#issuecomment-1201046738_

**Comment by tznind** [comment]
@BDisp is this in the PosEditor and DimEditor dialogs?

**Comment by BDisp** [comment]
> @BDisp is this in the PosEditor and DimEditor dialogs?

Yes, but perhaps can have the same behavior on others places where `ComboBox` is used.

**Comment by tznind** [comment]
Do you think this is something better handled in gui.cs? I feel like anything I implement in mouse click event handler is going to be hacky?  Especially since ComboBox doesn't expose its listbox property.

**Comment by BDisp** [comment]
Totally agree with you. All the bugs that is pertinent to the gui.cs must be fixed there. I just was talking about this with you to exchange ideas. Can you open an issue there, please. Only if you think this worth something, of course.

**Comment by BDisp** [comment]
Well, the new Terminal.Gui package allow this now.

**Comment by tznind** [comment]
Great stuff! new combo boxes are working great 🎉
