### ISSUE TITLE
Mouse 'sticky' and unresponsive in Linux

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#66]
Workaround is to run with the command line parameter `--usc` 

Running without this setting seems to result in the mouse getting 'attached' to things that you are trying to drag making them impossible to drop even after releasing the mouse button.  Starting drags also seems sluggish without `--usc`.

**Comment by BDisp** [comment]
I recommend to use the `Linux Mint` which has a better performance than the `Ubuntu` or `Debian`, where the mouse works well.
