### ISSUE TITLE
Cannot 'click drag' resize TabView when tabs are on bottom

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#76]
![image](https://user-images.githubusercontent.com/31306100/187144599-f36a3228-552a-4a41-80e9-fb6c2611a1b1.png)

Clicking and dragging in lower right of bottom `TabView` does not initiate a resize event.

**Comment by tznind** [comment]
`TabView` has 2 child views.  The first is a private class `TabRowView` and shows the selected tab name and other tab names.  It handles clicks on tabs.  The second is also private and is the 'content' area of the `Tabview` and hosts the currently selected `Tab`

Part of the deliberate design of `TabView` is that clicks outside of the 'tabs' in `TabRowView` are not captured.  This may be due to the size of `TabRowView` or because it deliberately discards clicks beyond the limit of its width.

This test shows this behavior (which is good)

```csharp

[Fact, AutoInitShutdown]
public void TestTabView_ClickThrough ()
{
	var tv = GetTabView (out _, out _, false);
	// tab view is very wide
	tv.Width = 40;
	tv.Height = 5;
	tv.LayoutSubviews ();

	tv.Redraw (tv.Bounds);

	// Required in order to focus the window
	Application.Top.Add(tv);

	GraphViewTests.AssertDriverContentsAre (@"
┌────┐
│Tab1│Tab2
│    └─────────────────────────────────┐
│hi                                    │
└──────────────────────────────────────┘
", output);
	tv.SetFocus();
	Assert.True(tv.HasFocus);

	
	var clickInTab2 = new MouseEvent{
		Flags = MouseFlags.Button1Clicked,
		X = 7,
		Y = 1
	};

	var clickInEmptySpace = new MouseEvent{
		Flags = MouseFlags.Button1Clicked,
		X = 30,
		Y = 1
	};
	
	Assert.Equal("Tab1",tv.SelectedTab.Text);

	// FYI for TabView Subviews[0] is the tab selection row
	// while Subviews[1] is the client area

	// when user clicks in the area of Tab2 the click is consumed
	// and the view moves to show tab2
	Assert.True(tv.Subviews[0].MouseEvent(clickInTab2));
	Assert.Equal("Tab2",tv.SelectedTab.Text);

	// Now comes the bit we really want to test.  What happens when
	// the user clicks in that big area of empty space to the right
	// of tab 2
	Assert.False(tv.Subviews[0].MouseEvent(clickInEmptySpace));
}
```
I am considering 2 approaches on this

- Make this 'click through' behavior optional in gui.cs
- Look for a workaround in designer to see if we can capture the event anyway

**Comment by tznind** [comment]
Setting `Style.ShowBorderLine` to false also breaks or makes very difficult the resizing.  

This issue may be better delayed until #86 is considered/implemented.  Having a clear border on the focused control with a resize box would probably invalidate this ticket as the resize code would change considerably

**Comment by BDisp** [comment]
Maybe you can capture it by using the `MouseClick` event which runs before the `MouseEvent` method and compare the current position click with the `TabRowView` dimension.
