### ISSUE TITLE
TabView controls tab order is not consistent with main app tab order

### ISSUE THREAD

**Issue by tznind** [gui-cs/TerminalGuiDesigner#78]
Terminal.Gui tab order between controls is dependent on the sequence in which they are added to the parent view.

TerminalGuiDesigner outputs controls in order of Ascending Y then X so that tab order is from top left to lower right.

https://github.com/gui-cs/TerminalGuiDesigner/blob/34d434d140923f30a76a1f46cdc87f84e2106496/src/ToCode/ViewToCode.cs#L224-L235
_Good code that outputs sensible tab order - btw we should remove this TODO it is no longer an issue thanks to https://github.com/gui-cs/TerminalGuiDesigner/pull/61_

However when views are in a `TabView` this behaviour is not the same and controls are instead output in the order they are specified in `.Designer.cs` which is typically the order the user added them to the tab view.  This becomes a problem when a user makes changes to an old tab view and inserts new controls in the middle of the View - these get a tab order of 'last' 

We need to centralise the order and update the following to use the centralised Order delegate:
https://github.com/gui-cs/TerminalGuiDesigner/blob/34d434d140923f30a76a1f46cdc87f84e2106496/src/ToCode/TabToCode.cs#L41-L48
_Bad code that outputs in arbitrary tab order_

To reproduce this issue

- Create a tab view
- Add 2 textfields with a bit of vertical space between them
- Close designer
- Reopen designer
- Insert another TextField in the middle
- Save
- Close and reopen

You would expect tab order to be top to bottom but instead goes top,bottom,middle

Doing the same thing outside of a TabView works correctly.

**Comment by BDisp** [comment]
I think the view position do not guarantee a tab order because it's handled by the `View.TabIndex` property. The user may want to change another tab order than the position. Should be a good idea to give to the user a way to change the `TabIndex` on the view properties UI.

**Comment by tznind** [comment]
Definetly.  I will create a new ticket for this.  Need to see how robust TabIndex is, whether it needs to be set after adding it to the View or if theres any other issues.  Presumably need to detect and handle collisions sensibly too within the Designer.

But this is quite a simple fix to make both bits of code consistent.  Then I will look at how best to give user direct control of TabIndex.

The Winforms Designer has a quite nice 'Tab Order' tool where you click on the controls in the order you want but probably don't have to go that far.

**Comment by BDisp** [comment]
I'm not sure if it has some bug on the `TabIndex` but if it has, probably will be on the views subviews.

**Comment by tznind** [comment]
Sorry I didn't mean to imply that `TabIndex` might be bugged; just that making it designable will involve testing how it responds to runtime changes and/or removing views etc.
